version: '3.8'

volumes:
  static_value:
  media_value:
  database:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: s3r3ga/yamdb_final:latest
    restart: always
    volumes:
      - type: volume
        source: static_value
        target: /app/static/
        volume:
          nocopy: false
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: static_value
        target: /var/html/static/
        volume:
          nocopy: false
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - media_value:/var/html/media/
    depends_on:
      - web
